version: '3'

volumes:
  objects_db:
    external: true

services:
  db:
    image: postgres
    command: "-c logging_collector=on"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=mydatabase
    volumes:
      - "objects_db:/var/lib/postgresql/data/"
    ports:
      - "5432:5432"


  backend:
    container_name: backend
    build: ./
    command: bash -c "cd backend/ && python manage.py migrate && python manage.py makemigrations && python manage.py runserver  0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=mydatabase
    depends_on:
      - db